/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dice;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author jf211124
 */
public class GUI extends javax.swing.JFrame
{

    /**
     * Creates new form GUI
     */
    public GUI()
    {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jRollButton = new javax.swing.JButton();
        jDieTypeTextField = new javax.swing.JTextField();
        jDieAmountTextField = new javax.swing.JTextField();
        jRollTypeComboBox = new javax.swing.JComboBox<>();
        jDieTypeLabel = new javax.swing.JLabel();
        jDieAmountLabel = new javax.swing.JLabel();
        jRollTypeLabel = new javax.swing.JLabel();
        jResultTitleLabel = new javax.swing.JLabel();
        jResultLabel = new javax.swing.JLabel();
        jSumLabel = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dice Roller");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(50, 50, 0, 67));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        setForeground(java.awt.Color.black);

        jRollButton.setText("Roll!");
        jRollButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRollButtonActionPerformed(evt);
            }
        });

        jDieTypeTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jDieTypeTextFieldActionPerformed(evt);
            }
        });

        jDieAmountTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jDieAmountTextFieldActionPerformed(evt);
            }
        });

        jRollTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Exploding", "Advantage", "Disadvantage" }));
        jRollTypeComboBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRollTypeComboBoxActionPerformed(evt);
            }
        });

        jDieTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDieTypeLabel.setText("Die Type");

        jDieAmountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDieAmountLabel.setText("Die Amount");

        jRollTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRollTypeLabel.setText("Roll Type");

        jResultTitleLabel.setText("Result: ");

        jResultLabel.setText("   ");
        jResultLabel.setToolTipText("Roll Result");
        jResultLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSumLabel.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDieTypeTextField)
                    .addComponent(jDieTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDieAmountTextField)
                    .addComponent(jDieAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRollTypeComboBox, 0, 93, Short.MAX_VALUE)
                    .addComponent(jRollTypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRollButton, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jResultTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDieTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDieAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRollButton)
                    .addComponent(jRollTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDieTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDieAmountLabel)
                    .addComponent(jResultTitleLabel)
                    .addComponent(jResultLabel)
                    .addComponent(jRollTypeLabel)
                    .addComponent(jSumLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRollButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRollButtonActionPerformed
    {//GEN-HEADEREND:event_jRollButtonActionPerformed
        if(jRollTypeComboBox.getSelectedItem().toString().equals("Default"))
        {
            if(Integer.parseInt(jDieAmountTextField.getText()) == 1)
            {
                int sumD = roll.rollDie(Integer.parseInt(jDieTypeTextField.getText()));
                jResultLabel.setText(Integer.toString(sumD));
                jSumLabel.setText("= " + Integer.toString(sumD));
            }
            else
            {
                int [] sumDA = roll.rollDice(Integer.parseInt(jDieTypeTextField.getText()), Integer.parseInt(jDieAmountTextField.getText()));
                jResultLabel.setText(Arrays.toString(sumDA));
                jSumLabel.setText("= " + Integer.toString(roll.sumResultsOne(sumDA)));
            }
        }
        else if(jRollTypeComboBox.getSelectedItem().toString().equals("Exploding"))
        {
            if(Integer.parseInt(jDieTypeTextField.getText()) == 1)
            {
                jResultLabel.setText("One-sided coin");
            }
            else if(Integer.parseInt(jDieAmountTextField.getText()) > 1)
            {
                int[][] sumE = roll.rollExplodeDice(Integer.parseInt(jDieTypeTextField.getText()), Integer.parseInt(jDieAmountTextField.getText()));
                jResultLabel.setText(roll.ExplodeDiceString(sumE));
                jSumLabel.setText("= " + Integer.toString(roll.sumResultsTwo(sumE)));
            }
            else
            {
                int[] sumEA = roll.rollExplodeDie(Integer.parseInt(jDieTypeTextField.getText()));
                jResultLabel.setText(Arrays.toString(sumEA));
                jSumLabel.setText("= " + Integer.toString(roll.sumResultsOne(sumEA)));
            }
        }
        else if(jRollTypeComboBox.getSelectedItem().toString().equals("Advantage"))
        {
            if(Integer.parseInt(jDieAmountTextField.getText()) > 1)
            {
                int[] sumA = roll.rollAdvantageDice(Integer.parseInt(jDieTypeTextField.getText()), Integer.parseInt(jDieAmountTextField.getText()));
                jResultLabel.setText(Arrays.toString(sumA));
                jSumLabel.setText("= " + Integer.toString(roll.sumResultsOne(sumA)));
            }
            else
            {
                int sumAA = roll.rollAdvantageDie(Integer.parseInt(jDieTypeTextField.getText()));
                jResultLabel.setText(Integer.toString(sumAA));
                jSumLabel.setText("= " + Integer.toString(sumAA));
            }
        }
        else if(jRollTypeComboBox.getSelectedItem().toString().equals("Disadvantage"))
        {
            if(Integer.parseInt(jDieAmountTextField.getText()) > 1)
            {
                int[] sumD2 = roll.rollDisadvantageDice(Integer.parseInt(jDieTypeTextField.getText()), Integer.parseInt(jDieAmountTextField.getText()));
                jResultLabel.setText(Arrays.toString(sumD2));
                jSumLabel.setText("= " + Integer.toString(roll.sumResultsOne(sumD2)));
            }
            else
            {
                int sumDD = roll.rollDisadvantageDie(Integer.parseInt(jDieTypeTextField.getText()));
                jResultLabel.setText(Integer.toString(sumDD));
                jSumLabel.setText("= " + Integer.toString(sumDD));
            }
        }
    }//GEN-LAST:event_jRollButtonActionPerformed

    private void jDieTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jDieTypeTextFieldActionPerformed
    {//GEN-HEADEREND:event_jDieTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDieTypeTextFieldActionPerformed

    private void jDieAmountTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jDieAmountTextFieldActionPerformed
    {//GEN-HEADEREND:event_jDieAmountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDieAmountTextFieldActionPerformed

    private void jRollTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRollTypeComboBoxActionPerformed
    {//GEN-HEADEREND:event_jRollTypeComboBoxActionPerformed
        
    }//GEN-LAST:event_jRollTypeComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GUI().setVisible(true);
            }
        });
    }
    DiceRoller roll = new DiceRoller();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jDieAmountLabel;
    private javax.swing.JTextField jDieAmountTextField;
    private javax.swing.JLabel jDieTypeLabel;
    private javax.swing.JTextField jDieTypeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JLabel jResultLabel;
    private javax.swing.JLabel jResultTitleLabel;
    private javax.swing.JButton jRollButton;
    private javax.swing.JComboBox<String> jRollTypeComboBox;
    private javax.swing.JLabel jRollTypeLabel;
    private javax.swing.JLabel jSumLabel;
    // End of variables declaration//GEN-END:variables
}
